import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://www.saucedemo.com/")
    page.locator("[data-test=\"login-container\"] div").filter(has_text="Login").first.click()
    page.locator("[data-test=\"login-button\"]").click()
    page.locator("[data-test=\"error\"]").click()
    page.locator("[data-test=\"username\"]").click()
    page.locator("[data-test=\"username\"]").fill("standard_user")
    page.locator("[data-test=\"password\"]").click()
    page.locator("[data-test=\"password\"]").fill("secret_sauce")
    page.locator("[data-test=\"login-button\"]").click()
    page.locator("[data-test=\"add-to-cart-sauce-labs-backpack\"]").click()
    page.locator("[data-test=\"add-to-cart-sauce-labs-bike-light\"]").click()
    page.get_by_text("$9.99").click()
    page.locator("[data-test=\"item-1-title-link\"]").click()
    page.locator("[data-test=\"inventory-item-desc\"]").click()
    page.locator("[data-test=\"inventory-item-price\"]").click()
    page.locator("[data-test=\"add-to-cart\"]").click()
    page.locator("[data-test=\"back-to-products\"]").click()
    page.get_by_text("$49.99").click()
    page.get_by_text("It's not every day that you").click()
    page.locator("[data-test=\"add-to-cart-sauce-labs-fleece-jacket\"]").click()
    page.locator("[data-test=\"add-to-cart-sauce-labs-onesie\"]").click()
    page.locator("[data-test=\"add-to-cart-test\\.allthethings\\(\\)-t-shirt-\\(red\\)\"]").click()
    page.get_by_text("$15.99").nth(1).click()
    page.get_by_text("$7.99Remove").click()
    page.get_by_text("$7.99").click()
    page.locator("[data-test=\"title\"]").click()
    page.get_by_role("button", name="Open Menu").click()
    page.get_by_text("Name (A to Z)Name (A to Z)").click()
    page.locator("[data-test=\"shopping-cart-link\"]").click()
    page.locator("[data-test=\"cart-list\"] div").filter(has_text="1Sauce Labs Backpackcarry.").locator("[data-test=\"item-quantity\"]").click()
    page.locator("[data-test=\"remove-sauce-labs-backpack\"]").click()
    page.get_by_text("$9.99").click()
    page.get_by_text("Sauce Labs Bike LightA red").click()
    page.locator("[data-test=\"item-0-title-link\"]").click()
    page.locator("[data-test=\"back-to-products\"]").click()
    page.locator("[data-test=\"shopping-cart-link\"]").click()
    page.locator("[data-test=\"continue-shopping\"]").click()
    page.locator("[data-test=\"shopping-cart-link\"]").click()
    page.locator("[data-test=\"checkout\"]").click()
    page.locator("[data-test=\"firstName\"]").click()
    page.locator("[data-test=\"firstName\"]").fill("taksh")
    page.locator("[data-test=\"firstName\"]").press("Tab")
    page.locator("[data-test=\"lastName\"]").fill("prajapati")
    page.locator("[data-test=\"lastName\"]").press("Tab")
    page.locator("[data-test=\"postalCode\"]").fill("603203")
    page.locator("[data-test=\"continue\"]").click()
    page.get_by_text("Sauce Labs Bike LightA red").click()
    page.get_by_text("Sauce Labs Bolt T-ShirtGet").click()
    page.get_by_text("Sauce Labs Fleece JacketIt's").click()
    page.locator("[data-test=\"payment-info-label\"]").click()
    page.locator("[data-test=\"payment-info-value\"]").click()
    page.locator("[data-test=\"shipping-info-label\"]").click()
    page.locator("[data-test=\"shipping-info-value\"]").click()
    page.locator("[data-test=\"total-info-label\"]").click()
    page.locator("[data-test=\"tax-label\"]").click()
    page.locator("[data-test=\"subtotal-label\"]").click()
    page.locator("[data-test=\"total-label\"]").click()
    page.locator("[data-test=\"finish\"]").click()
    page.locator("[data-test=\"complete-header\"]").click()
    page.locator("[data-test=\"pony-express\"]").click()
    page.locator("[data-test=\"complete-text\"]").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
